<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.laborcraft</groupId>
    <artifactId>discmesg</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>discmesg</name>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <defaultGoal>clean package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <minimizeJar>true</minimizeJar>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <relocations>
                                <relocation>
                                    <pattern>com.fasterxml.jackson</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.com.fasterxml.jackson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.crypto.tink</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.com.google.crypto.tink</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.errorprone.annotations</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.com.google.errorprone.annotations</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.google.gson</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.com.google.gson</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.neovisionaries</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.com.neovisionaries</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>com.sun.jna</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.com.sun.jna</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>gnu.trove</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.gnu.trove</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>google.protobuf</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.google.protobuf</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>natives</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.natives</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>net.dv8tion</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.net.dv8tion</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>okhttp3</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.okhttp3</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>okio</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.okio</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.apache.commons.collections4</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.org.apache.commons.collections4</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>org.intellij.lang.annotations</pattern>
                                    <shadedPattern>net.laborcraft.discmesg.lib.org.intellij.lang.annotations</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>papermc-repo</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>5.3.2</version>
            <exclusions>
                <exclusion>
                    <groupId>club.minnced</groupId>
                    <artifactId>opus-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <version>2.11.2</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
